In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [2]:
dic_symptoms = {'abdominal_pain': 0,
 'abnormal_menstruation': 1,
 'acidity': 2,
 'acute_liver_failure': 3,
 'altered_sensorium': 4,
 'anxiety': 5,
 'back_pain': 6,
 'belly_pain': 7,
 'blackheads': 8,
 'bladder_discomfort': 9,
 'blister': 10,
 'blood_in_sputum': 11,
 'bloody_stool': 12,
 'blurred_and_distorted_vision': 13,
 'breathlessness': 14,
 'brittle_nails': 15,
 'bruising': 16,
 'burning_micturition': 17,
 'chest_pain': 18,
 'chills': 19,
 'cold_hands_and_feets': 20,
 'coma': 21,
 'congestion': 22,
 'constipation': 23,
 'continuous_feel_of_urine': 24,
 'continuous_sneezing': 25,
 'cough': 26,
 'cramps': 27,
 'dark_urine': 28,
 'dehydration': 29,
 'depression': 30,
 'diarrhoea': 31,
 'dischromic _patches': 32,
 'distention_of_abdomen': 33,
 'dizziness': 34,
 'drying_and_tingling_lips': 35,
 'enlarged_thyroid': 36,
 'excessive_hunger': 37,
 'extra_marital_contacts': 38,
 'family_history': 39,
 'fast_heart_rate': 40,
 'fatigue': 41,
 'fluid_overload': 42,
 'foul_smell_of urine': 43,
 'headache': 44,
 'high_fever': 45,
 'hip_joint_pain': 46,
 'history_of_alcohol_consumption': 47,
 'increased_appetite': 48,
 'indigestion': 49,
 'inflammatory_nails': 50,
 'internal_itching': 51,
 'irregular_sugar_level': 52,
 'irritability': 53,
 'irritation_in_anus': 54,
 'joint_pain': 55,
 'knee_pain': 56,
 'lack_of_concentration': 57,
 'lethargy': 58,
 'loss_of_appetite': 59,
 'loss_of_balance': 60,
 'loss_of_smell': 61,
 'malaise': 62,
 'mild_fever': 63,
 'mood_swings': 64,
 'movement_stiffness': 65,
 'mucoid_sputum': 66,
 'muscle_pain': 67,
 'muscle_wasting': 68,
 'muscle_weakness': 69,
 'nausea': 70,
 'neck_pain': 71,
 'nodal_skin_eruptions': 72,
 'obesity': 73,
 'pain_behind_the_eyes': 74,
 'pain_during_bowel_movements': 75,
 'pain_in_anal_region': 76,
 'painful_walking': 77,
 'palpitations': 78,
 'passage_of_gases': 79,
 'patches_in_throat': 80,
 'phlegm': 81,
 'polyuria': 82,
 'prominent_veins_on_calf': 83,
 'puffy_face_and_eyes': 84,
 'pus_filled_pimples': 85,
 'receiving_blood_transfusion': 86,
 'receiving_unsterile_injections': 87,
 'red_sore_around_nose': 88,
 'red_spots_over_body': 89,
 'redness_of_eyes': 90,
 'restlessness': 91,
 'runny_nose': 92,
 'rusty_sputum': 93,
 'scurring': 94,
 'shivering': 95,
 'silver_like_dusting': 96,
 'sinus_pressure': 97,
 'skin_peeling': 98,
 'skin_rash': 99,
 'slurred_speech': 100,
 'small_dents_in_nails': 101,
 'spinning_movements': 102,
 'spotting_ urination': 103,
 'stiff_neck': 104,
 'stomach_bleeding': 105,
 'stomach_pain': 106,
 'sunken_eyes': 107,
 'sweating': 108,
 'swelled_lymph_nodes': 109,
 'swelling_joints': 110,
 'swelling_of_stomach': 111,
 'swollen_blood_vessels': 112,
 'swollen_extremeties': 113,
 'swollen_legs': 114,
 'throat_irritation': 115,
 'toxic_look_(typhos)': 116,
 'ulcers_on_tongue': 117,
 'unsteadiness': 118,
 'visual_disturbances': 119,
 'vomiting': 120,
 'watering_from_eyes': 121,
 'weakness_in_limbs': 122,
 'weakness_of_one_body_side': 123,
 'weight_gain': 124,
 'weight_loss': 125,
 'yellow_crust_ooze': 126,
 'yellow_urine': 127,
 'yellowing_of_eyes': 128,
 'yellowish_skin': 129,
 'itching': 130}

In [3]:
symptom_list = []
index_list = []
for key,value in dic_symptoms.items():
    symptom_list.append(key)
    index_list.append(value)

In [4]:
symptom_list

['abdominal_pain',
 'abnormal_menstruation',
 'acidity',
 'acute_liver_failure',
 'altered_sensorium',
 'anxiety',
 'back_pain',
 'belly_pain',
 'blackheads',
 'bladder_discomfort',
 'blister',
 'blood_in_sputum',
 'bloody_stool',
 'blurred_and_distorted_vision',
 'breathlessness',
 'brittle_nails',
 'bruising',
 'burning_micturition',
 'chest_pain',
 'chills',
 'cold_hands_and_feets',
 'coma',
 'congestion',
 'constipation',
 'continuous_feel_of_urine',
 'continuous_sneezing',
 'cough',
 'cramps',
 'dark_urine',
 'dehydration',
 'depression',
 'diarrhoea',
 'dischromic _patches',
 'distention_of_abdomen',
 'dizziness',
 'drying_and_tingling_lips',
 'enlarged_thyroid',
 'excessive_hunger',
 'extra_marital_contacts',
 'family_history',
 'fast_heart_rate',
 'fatigue',
 'fluid_overload',
 'foul_smell_of urine',
 'headache',
 'high_fever',
 'hip_joint_pain',
 'history_of_alcohol_consumption',
 'increased_appetite',
 'indigestion',
 'inflammatory_nails',
 'internal_itching',
 'irregular_sug

In [5]:
interpreter = tf.lite.Interpreter(model_path="disease.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']


arr = np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=np.float32)


user_input_list =  input().split()
print(user_input_list)

num_list = []

for i in user_input_list:
    if i in symptom_list:
        index = symptom_list.index(i)
        num_list.append(index)
for i in num_list:
    arr[i] = 1

input_data = arr.reshape(input_shape)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])


[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
['[0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,', '0.,

In [6]:
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [7]:
dis_place = np.where(output_data == np.max(output_data))
print(dis_place)
print(dis_place[1][0])
output_data[0][18]
output_data

(array([0], dtype=int64), array([18], dtype=int64))
18


array([[0.33209792, 0.33608633, 0.01815267, 0.00966791, 0.1360125 ,
        0.02858438, 0.01493636, 0.02861791, 0.00617136, 0.07445936,
        0.01799453, 0.04328138, 0.07564449, 0.00448785, 0.04294119,
        0.30954713, 0.00497817, 0.20440835, 0.40363157, 0.05219819,
        0.00673435, 0.0833499 , 0.01209812, 0.01390012, 0.1897353 ,
        0.00561392, 0.3467625 , 0.06332286, 0.04208455, 0.37492424,
        0.00976057, 0.0919816 , 0.03993507, 0.07002789, 0.00950788,
        0.01614236, 0.28297335, 0.07874627, 0.16081002, 0.00947394,
        0.30830902]], dtype=float32)

In [8]:
dic = {0: 'Urinary tract infection',1: 'Gastroenteritis', 2: 'Hypothyroidism', 3: 'Chicken pox', 4: 'Cervical spondylosis',
 5: 'Migraine',
 6: 'Hepatitis B',
 7: 'Diabetes ',
 8: 'Hepatitis E',
 9: 'Bronchial Asthma',
 10: 'Hyperthyroidism',
 11: '(vertigo) Paroymsal  Positional Vertigo',
 12: 'Varicose veins',
 13: 'Dengue',
 14: 'Chronic cholestasis',
 15: 'Paralysis (brain hemorrhage)',
 16: 'Tuberculosis',
 17: 'Hepatitis C',
 18: 'Allergy',
 19: 'Alcoholic hepatitis',
 20: 'Typhoid',
 21: 'Hypertension ',
 22: 'Malaria',
 23: 'Jaundice',
 24: 'Dimorphic hemmorhoids(piles)',
 25: 'Hepatitis D',
 26: 'Heart attack',
 27: 'Osteoarthristis',
 28: 'Drug Reaction',
 29: 'AIDS',
 30: 'Hypoglycemia',
 31: 'Impetigo',
 32: 'GERD',
 33: 'Psoriasis',
 34: 'Pneumonia',
 35: 'hepatitis A',
 36: 'Acne',
 37: 'Peptic ulcer diseae',
 38: 'Arthritis',
 39: 'Common Cold',
 40: 'Fungal infection'}

print(dic[dis_place[1][0]])

Allergy


In [9]:
import pickle

In [10]:
infile = open('./drug_symptom_model.pickle','rb')
new_dict = pickle.load(infile)
infile.close() 


C:\Users\choud\anaconda3\lib\site-packages\sklearn\base.py:324: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.2 when using version 1.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\choud\anaconda3\lib\site-packages\sklearn\base.py:324: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.23.2 when using version 1.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [22]:
arr = np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=np.float32)

print(arr.shape)
user_input_list =  input().split()
print(user_input_list)
#print(user_input_list)
num_list = []

for i in user_input_list:
    if i in dic_symptoms.keys():
        num_list.append(dic_symptoms[i])
        
for i in num_list:
    arr[i] = 1
new_dict.predict([arr])

(131,)
mild_fever indigestion cough
['mild_fever', 'indigestion', 'cough']


array(['Peptic ulcer diseae'], dtype=object)